### ISSUE TITLE
Basic networking foundation

### ISSUE THREAD

**Issue by chocolatemelt** [chocolatemelt/kadopon-server#175]
Nothing so sophisticated, but a good start could be pattern matching, packing/unpacking, and a message queue. A separate thread for processing messages would probably be best?

**Comment by jungj5** [comment]
got links to any docs you've been looking at?

**Comment by chocolatemelt** [comment]
https://gamedev.stackexchange.com/questions/98533/how-do-i-create-a-multiplayer-server-also-suitable-for-local-single-player

https://gafferongames.com/post/what_every_programmer_needs_to_know_about_game_networking/

https://github.com/amzeratul/halley/tree/master/src/plugins/asio/src

https://gamedev.stackexchange.com/questions/126481/how-to-organize-messages-queue-in-a-fast-paced-multiplayer-game
